name: tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Dependencies
        run: go mod download

      - name: Lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.49.0
          ./bin/golangci-lint run

      - name: Test
        run: go test -race -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Coverage
        uses: codecov/codecov-action@v1.0.13
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
